services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt:rw
      - ./html:/var/www/certbot:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email parkdanilssafy@gmail.com --agree-tos --no-eff-email --force-renewal -d myocean.cloud -d be.myocean.cloud -d data2.myocean.cloud
