global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (서버 리소스)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (컨테이너 모니터링)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # MinIO 클러스터 메트릭
  - job_name: 'minio-cluster'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets:
          - 'minio1:9000'
          - 'minio2:9000'
          - 'minio3:9000'
          - 'minio4:9000'
    scrape_interval: 30s

  # MinIO 노드별 메트릭
  - job_name: 'minio-node'
    metrics_path: /minio/v2/metrics/node
    static_configs:
      - targets:
          - 'minio1:9000'
          - 'minio2:9000'
          - 'minio3:9000'
          - 'minio4:9000'
    scrape_interval: 30s